# Configuration
variables:
  OUTPUTDIR: _build
  PROD_URL: https://docs.opsone.ch/6-0-stable/
  STAGE_URL: https://test.docs.opsone.ch/6-0-stable/
  VERSION: 6-0-stable

# Docker image
image: "python:latest"

# Define stages
stages:
- deploy stage
- deploy prod
- test

# Dependencies
before_script:
  # SSH deploy key
  - apt-get update
  - 'which ssh-agent || apt-get -y install openssh-client'
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

include:
  - .gitlab/ci/deploy_stage.yml
  - .gitlab/ci/deploy_prod.yml
  - .gitlab/ci/linkchecker.yml
