---
# configuration
image: python:3-slim
variables:
  OUTPUTDIR: _build
  STAGE_URL: https://test.docs.opsone.ch/7-0-stable/
  VERSION: 7-0-stable

# stages
stages:
  - deploy_test
  - linkcheck
  - deploy_prod

# hidden job template used on prod and stage
.build_sphinx: &build_sphinx
  # load SSH deploy key
  - apt-get update
  - 'which ssh-agent || apt-get -y install openssh-client'
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  # install dependencies
  - apt-get -y install rsync
  - pip install Sphinx==3.0.0b1
  - pip install sphinx_rtd_theme
  # build documentation
  - sphinx-build . $OUTPUTDIR

deploy_prod:
  # TODO: remove
  when: manual
  stage: deploy_prod
  environment: PROD
  only:
    - 7-0-stable@platform/docs
  script:
    - *build_sphinx
    - rsync -avz --delete $OUTPUTDIR/ ${PROD_USERNAME}@${PROD_SERVERNAME}:~/www/${CI_BUILD_REF_NAME}/

deploy_test:
  stage: deploy_test
  environment: test
  script:
    - *build_sphinx
    - rsync -avz --delete $OUTPUTDIR/ ${STAGE_USERNAME}@${STAGE_SERVERNAME}:~/www/${CI_BUILD_REF_NAME}/

linkcheck:
  image: debian:10
  stage: linkcheck
  allow_failure: true
  script:
    - apt -y install linkchecker
    - mkdir -p ~/.linkchecker
    - echo -e "[authentication]\nentry=${STAGE_URL} ${BASICAUTH_USERNAME} ${BASICAUTH_PASSWORD}" > ~/.linkchecker/linkcheckerrc
    - linkchecker --no-warnings $STAGE_URL

